language: node_js
node_js:
  - '8'
cache:
  directories:
    - node_modules
install:
  - npm install -g firebase-tools
  - npm install -g eslint
script:
  - npm run lint
  - npm install
  - npm run build
  - npm test

after_success:
  - test $TRAVIS_BRANCH = "master" && firebase deploy --token $FIREBASE_TOKEN